### PR TITLE
added Contributing.md

### PR DESCRIPTION
**Pull request by NIKU-SINGH**
Added an instruction for Bot usage and updated the contributor's list.
@all-contributors please add @samanyougarg  for Code

### CODE REVIEW

**Comment by Gupta-Anubhav12** [comment]
I am unable to understand how this thing might work !,
could you please explain this in some detail like how the bot is authenticated to make a PR into repo and add anyone as a contributor who just comments on some issue or PR,
This also might invite spam during periods like hacktoberfest

**Comment by NIKU-SINGH** [comment]
I am fairly new to this. I just followed the documentation.
What I did was I created a new repo on my profile and gave bot access to it and then created an issue to add me as a contributor which it did, along with photo and emoji.

I thought this would be the same case with the Bhagavad Gita repo if the bot is given access, so I wrote the instruction to use the bot, if anyone wants to be added they can open an issue and the bot will create a pull request which owner can verify and merge it.

> I am unable to understand how this thing might work !,
> could you please explain this in some detail like how the bot is authenticated to make a PR into repo and add anyone as a contributor who just comments on some issue or PR,
> This also might invite spam during periods like hacktoberfest

**Comment by samanyougarg** [comment]
@NIKU-SINGH Thanks for looking into this issue.

I believe all we have to do was to install the bot at the organization level for `gita`.

Then, one of the org admins can comment on an Issue or Pull Request, asking @all-contributors to add a contributor. The bot will then create a Pull Request to add the contributor, then reply with the pull request details. Fairly straightforward.

Do you mind updating the existing `contributing.md` with the steps you mentioned rather than creating a new one?
Our current `contributing.md` is in `.github/contributing.md`.

**Comment by NIKU-SINGH** [comment]
> @NIKU-SINGH Thanks for looking into this issue.
> 
> I believe all we have to do was to install the bot at the organization level for `gita`.
> 
> Then, one of the org admins can comment on an Issue or Pull Request, asking @all-contributors to add a contributor. The bot will then create a Pull Request to add the contributor, then reply with the pull request details. Fairly straightforward.
> 
> Do you mind updating the existing `contributing.md` with the steps you mentioned rather than creating a new one?
> Our current `contributing.md` is in `.github/contributing.md`.

Ya sure, I will do that

**Pull request closed without merging**
