### PR TITLE
Restructure Project + Refactor Code + Bug fixes

### PR DESCRIPTION
**Pull request by samanyougarg**
- Fix models and schemas
- Restructure project
- Refactor code
- Bug fixes for other things
- Remove security vulnerability regarding SQL connection
- Added linting, pre-commit hooks etc.

### CODE REVIEW

**Comment by aahnik** [comment]
Hi @samanyougarg I don't understand what you are doing with multiple repos? If you wanted to experiment, why not use a branch ? Just curious to know your purpose .. 😊

- This repo contains a lot of pycache files, and other junk. Why not delete this one, and rename the v2 repo ? Some contributors committed those files, and that badly skews github's  stats. more lines of junk than actual code!

- And why the data is inside the repo ? Lets keep the data in a database. Commiting them in the repo is not a good idea IMO.

- I think using mongo db will be best. Thinking objects and json is more natural for modern applications. In mongo db schema changes will be easier. Mongodb with odmantic(based on pydantic) gives a fantastic and modern experience.

  - The mongo db atlas app gui can help us to transport the json files to mongo db database.
  
  - for getting started the mongo db atlas free tier offers 512 mb storage. I hope that will be sufficient for all contributors to experiment, and test.

**Comment by aahnik** [comment]
Some points regarding the `bug-fixes` branch of this repo.

- the `src` should contain packages. or the packages can stay in the root of the project. but here I see, `src` itself is a package, as it contains `__init__.py`. A package with the name `src` looks bad. Imo, we can name the package `bhagavad-gita` and publish to pypi. We can also make a minimal cli for that. People can `pip install bhagavad-gita` and then run `bhagavad-gita` in their terminal to start the server. that will be a cool experience.

- writing the project structure in the readme makes no sense. the project itself has the structure, people can explore the directory tree from github, or from their terminal or code editor. why waste space of the readme ? some other important info can take that space. its like this 
    ```python
       x = 1
       # x is assigned the value 1
    ```

- we have models(with sqlalchemy) and schemas(pydantic). why do double work ? [odmantic](https://github.com/art049/odmantic) is perfect for our use case.

**Review by Gupta-Anubhav12 — COMMENTED** [review]
me and @sanujsood  will complete the GQL thing asap for now after this merge to open that endpoint , we'll need to add the authentication there too in accordance to the rest to work concurrently

**Comment by samanyougarg** [comment]
Hi @aahnik, thanks for your feedback and suggestions.

> I don't understand what you are doing with multiple repos? If you wanted to experiment, why not use a branch ? Just curious to know your purpose ..

Earlier I was going to make the other repo the main one but later decided to just keep this one.

> This repo contains a lot of pycache files, and other junk. Why not delete this one, and rename the v2 repo ? Some contributors committed those files, and that badly skews github's stats. more lines of junk than actual code!

Those files have already been cleared up now. Github's stats don't really matter. We are all just trying to build something worthwhile here. I don't think anyone cares about who contributed the most and similar stats.

> I think using mongo db will be best. Thinking objects and json is more natural for modern applications. In mongo db schema changes will be easier. Mongodb with odmantic(based on pydantic) gives a fantastic and modern experience.

We have chosen Postgres over Mongo after a long discussion so would like to stick with it now. NoSQL is good but doesn't compare to SQL databases in terms of data integrity etc. Right now, we just have JSON data but for a later version, we will need to store user-specific data and other forms of data.


> the src should contain packages. or the packages can stay in the root of the project. but here I see, src itself is a package, as it contains __init__.py. A package with the name src looks bad. Imo, we can name the package bhagavad-gita and publish to pypi. We can also make a minimal cli for that. People can pip install bhagavad-gita and then run bhagavad-gita in their terminal to start the server. that will be a cool experience.

Sounds good, would you like to take that on and submit a PR?

> writing the project structure in the readme makes no sense. the project itself has the structure, people can explore the directory tree from github, or from their terminal or code editor. why waste space of the readme ? some other important info can take that space. its like this

Hmm, makes sense. Will remove that.

> we have models(with sqlalchemy) and schemas(pydantic). why do double work ? odmantic is perfect for our use case.

Isn't odmantic for MongoDB rather than SQL databases?

**Pull request merged**
