### PR TITLE
:rocket: feat--Gita-Transliteration

### PR DESCRIPTION
**Pull request by Srishtikumari2002**
# Description

I have added transliterations in the API. I have created a new model named `GitaTransliteration` in `models/gita.py` and added schemas for the respective model in `models/schemas.py` and have created `transliterations.py` to add data in the databse from the github repo.
* Have used `feat--new-languages` branch of `gita/gita` repo for data.

# Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Gupta-Anubhav12** [comment]
Hey @Srishtikumari2002 This is really great and cool
but there is one more thing that has to be done before merging this,
this won't go to main because it has introduced a breaking change 
one thing that is missing is to remove the old transliterations, the english ones refer [here](https://github.com/Srishtikumari2002/bhagavad-gita-api/blob/405eb84ee634c0d5d55b21aaadd11a0010cfa84c/bhagavad_gita_api/models/schemas.py#L38)

and we will have to merge current english transliterations from verse.json to transliterations file 
then we'll be good to roll out this as an update with multiple language support

**Comment by Gupta-Anubhav12** [comment]
> Hey @Srishtikumari2002 This is really great and cool but there is one more thing that has to be done before merging this, this won't go to main because it has introduced a breaking change one thing that is missing is to remove the old transliterations, the english ones refer [here](https://github.com/Srishtikumari2002/bhagavad-gita-api/blob/405eb84ee634c0d5d55b21aaadd11a0010cfa84c/bhagavad_gita_api/models/schemas.py#L38)
> 
> and we will have to merge current english transliterations from verse.json to transliterations file then we'll be good to roll out this as an update with multiple language support

basically what we need to do right now is to remove english transliterations from verse schema and to add that into transliterations schema, where all other languages are

**Comment by Srishtikumari2002** [comment]
Hey, I have cleaned the json data in `feat--new-languages`  branch of repo `gita/gita` and made required changes into the code as well. I think now we are good to go for an update.

**Comment by Gupta-Anubhav12** [comment]
Hey,
This works well, merging now 
so we can get this merged and get a we're ready for v2 :partying_face:

**Pull request merged**
