### PR TITLE
GraphQL refactored and refined 

### PR DESCRIPTION
**Pull request by Gupta-Anubhav12**
Added graphql support and removed some database bugs too , there are now nested graphql root queries with filters at each level , more filters and root queries can be added if required 
thanks

### CODE REVIEW

**Comment by samanyougarg** [comment]
@Gupta-Anubhav12 Did you install and run the pre-commit hooks before pushing?

Please see the [contributing guide](https://github.com/gita/bhagavad-gita-api/blob/main/.github/CONTRIBUTING.md) for reference.

**Review by sanujsood — APPROVED** [review]

**Comment by samanyougarg** [comment]
~~Getting an error when seeding the database on application start for `data/commentaries.py`:~~

~~`json.decoder.JSONDecodeError: Unterminated string starting at: line 11985 column 24 (char 1169686)`~~

~~Is anyone else getting the same?~~

Actually, tried again and I no longer get that error but there's a new error:
Screenshot 2021-07-06 at 5 06 44 PM

The verses table doesn't have a field called `verse_id` that is being referenced in `./bhagavad_gita_api/data/insert/commentaries.py`. Please change it to `id` or `verse_number` whichever one is relavant.

@Gupta-Anubhav12 @sanujsood

**Comment by sanujsood** [comment]
> ~Getting an error when seeding the database on application start for `data/commentaries.py`:~
> 
> ~`json.decoder.JSONDecodeError: Unterminated string starting at: line 11985 column 24 (char 1169686)`~
> 
> ~Is anyone else getting the same?~
> 
> Actually, tried again and I no longer get that error but there's a new error:
> Screenshot 2021-07-06 at 5 06 44 PM
> 
> The verses table doesn't have a field called `verse_id` that is being referenced in `./bhagavad_gita_api/data/insert/commentaries.py`. Please change it to `id` or `verse_number` whichever one is relavant.
> 
> @Gupta-Anubhav12 @sanujsood

image
It's working fine for me using in memory sqlite, probably there is some issue in  your database
@samanyougarg

**Comment by samanyougarg** [comment]
@sanujsood Did you try after rebasing with `main`?

`gita_verses` table doesn't have a column called `verse_id`. It was removed in a previous commit.

Screenshot 2021-07-06 at 9 25 40 PM

**Comment by Gupta-Anubhav12** [comment]
> @sanujsood Did you try after rebasing with `main`?
> 
> `gita_verses` table doesn't have a column called `verse_id`. It was removed in a previous commit.
> 
> Screenshot 2021-07-06 at 9 25 40 PM




verse_id was never a part of Verse schema , the error states that the verse_id from commentaries schema (where it exist) is not found in verse table means there is no verse.id =1 in verse table to link a commentary tuple that has verse_id as 1 ,
so this marks inconsistency in data not the code

attaching below the original schema that we developed before refactoring or any commits (the detta version) 
image



Hope this drops the misinterpretation about the error , @sanujsood  searched the and corrected about right interpretation , I was just to change the code replacing the verse_id in confused state

## so the original meaning of the error comes out to be
<hr>

The database is unable to link a commentary tuple which has verse_id = 1 to a verse which has id = 1 , so this means there is inconsistent data in existing database probably

see this is the verse_id that's being talked of and it is a foriegn key to verse table's primary key that's the verse.id

image

**Comment by Gupta-Anubhav12** [comment]
So we kinda figured out the issue ,
as suggested by @aahnik we got the json dump from a readymade database and that already had data and sqlite is not ACID compliant fully but postgress is , and we are adding commentaries before verses in database using script
so the commentaries are not able to find verses to make a foriegn key for linking 
that's where it works at our end (sqlite) and fails at your end (postgress) 

Let me commit again by making this change in order

**Comment by samanyougarg** [comment]
Yes, that makes sense.

My bad that I somehow misinterpreted the error.

From the points you mentioned above, yes inserting the commentaries before the verses would cause that error due to the verses table being empty.

Please fix it at your convenience.

Additionally, please remove the reference scripts if we don't need them.

**Comment by sanujsood** [comment]
updated the insertion order and tried running with postgres , it worked fine.

**Comment by samanyougarg** [comment]
@sanujsood There wasn't any change in the order in this commit https://github.com/gita/bhagavad-gita-api/pull/13/commits/86ce5cbc15d4a529c231c280fa8f5de5010ccd92
Still getting the same error since commentaries are being inserted before verses.

**Comment by samanyougarg** [comment]
Closing this one. Please see #26.

**Pull request closed without merging**
